logging:
  level:
    root: info

spring:
  application:
    name: feed
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8887

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: snp-feed

management:
  endpoint:
    shutdown:
      enabled: true